Registrar/Models/Department.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Registrar.Models
{
  public class Department
  {
    public int DepartmentId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public List<StudentDepartment> JoinEntities { get; }
    public ApplicationUser User { get; set; }
  }
}

Registrar/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Registrar.Controllers
{
  [Authorize]
  public class DepartmentsController : Controller
  {
    private readonly RegistrarContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    
    public DepartmentsController(UserManager<ApplicationUser> userManager, RegistrarContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    
    public async Task<ActionResult> Index()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      List<Department> userDepartments = _db.Departments
                                      .Where(entry => entry.User.Id == currentUser.Id)
                                      .ToList();
      return View(userDepartments);
    }
    
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Department department)
    {
      if (!ModelState.IsValid)
      {
        return View(department);
      }
      else{
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        department.User = currentUser;
        _db.Departments.Add(department);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      
    }
    
    public ActionResult Details(int id)
    {
      Department thisDepartment = _db.Departments
        .Include(department => department.JoinEntities)
        .ThenInclude(join => join.Student)
        .FirstOrDefault(department => department.DepartmentId == id);
      return View(thisDepartment);
    }

    public ActionResult AddStudent(int id)
    {
      Department thisDepartment = _db.Departments.FirstOrDefault(departments => departments.DepartmentId == id);
      ViewBag.StudentId = new SelectList(_db.Students, "StudentId", "Name");
      return View(thisDepartment);
    }

    [HttpPost]
    public ActionResult AddStudent(Department department, int studentId)
    {
      #nullable enable
      StudentDepartment? joinEntity = _db.StudentDepartments.FirstOrDefault(join => (join.StudentId == studentId && join.DepartmentId == department.DepartmentId));
      #nullable disable
      if (joinEntity == null && studentId != 0)
      {
        _db.StudentDepartments.Add(new StudentDepartment() { StudentId = studentId, DepartmentId = department.DepartmentId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = department.DepartmentId });
    }

    public ActionResult Edit(int id)
    {
      Department thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
      return View(thisDepartment);
    }

    [HttpPost]
    public ActionResult Edit(Department department)
    {
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Department thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
      return View(thisDepartment);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Department thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
      _db.Departments.Remove(thisDepartment);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      StudentDepartment joinEntry = _db.StudentDepartments.FirstOrDefault(entry => entry.StudentDepartmentId == joinId);
      _db.StudentDepartments.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
  }
}

Registrar/Views/Departments/AddStudent.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Department

<h2>Add a Student</h2>


<h3>Add a student to this department : @Html.DisplayFor(model => model.Name)</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DepartmentId)

  @Html.Label("Select a Student")
  @Html.DropDownList("StudentId")

  <input type ="submit" value="Save" />
}

<div>
  <div class="outside_side_bar">
    <div class="side_bar">
      <header>Epic Navi:</header>
      <br>
      <span>@Html.ActionLink("Back to list", "Index")</span>
      <br>
      <span>@Html.ActionLink("Home", "Index", "Home")</span>
    </div>
  </div>
</div>
<br>

Registrar/Views/Departments/Create.cshtml
@{
  Layout="_Layout";
}

@model Registrar.Models.Department

<h2>Add a new Department</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)

  <input type="submit" value="Add new department" class="btn btn-default"/>
}

<div>
  <div class="outside_side_bar">
    <div class="side_bar">
      <label>Epic Navi:</label>
      <br>
      <span>@Html.ActionLink("Show all Departments", "Index")</span>
      <br>
      <span>@Html.ActionLink("Home", "Index", "Home")</span>
    </div>
  </div>
</div>
<br>

Registrar/Views/Departments/Delete.cshtml
@{
  Layout="_Layout";
}

@model Registrar.Models.Department

<h2>Delete this obsolete department?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}

<div>
  <div class="outside_side_bar">
    <div class="side_bar">
      <header>Epic Navi:</header>
      <br>
      <span>@Html.ActionLink("Back to List", "Index")</span>
      <br>
      <span>@Html.ActionLink("Home", "Index", "Home")</span>
    </div>
  </div>
</div>
<br>

Registrar/Views/Departments/Details.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models
@model Registrar.Models.Department

<h2>Department Details</h2>
<hr />

<h3>@Html.DisplayNameFor(model => model.Name) : @Html.DisplayFor(model => model.Name) </h3>

@if(@Model.JoinEntities.Count == 0)

{
  <p> This Department does not have any students </p>
}
else
{
<h4>Students that belong to Department: </h4>
<ul>
@foreach(StudentDepartment join in Model.JoinEntities)
{
  <li>@join.Student.Name</li>
  @using(Html.BeginForm("DeleteJoin","Departments"))
  {
    @Html.Hidden("joinId", @join.StudentDepartmentId)
    <input type="submit" value="Delete"/>
  }
}
</ul>

}

<div>
  <div class="outside_side_bar">
    <div class="side_bar">
      <header>Epic Navi:</header>
      <br>
      <span>@Html.ActionLink("Home", "Index", "Home")</span>
      <br>
      <span>@Html.ActionLink("Back to list", "Index")</span>
      <br>
      <span>@Html.ActionLink("Add a Student", "AddStudent", new{ id = Model.DepartmentId })</span>
      <br>
      <span>@Html.ActionLink("Edit Department", "Edit", new{ id = Model.DepartmentId })</span>
      <br>
      <span>@Html.ActionLink("Delete Department", "Delete", new{ id = Model.DepartmentId })</span>
    </div>
  </div>
</div>
<br>

Registrar/Views/Departments/Edit.cshtml
@{
  Layout="_Layout";
}

@model Registrar.Models.Department

<h2>Edit Department</h2>

<h4>Edit this department: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DepartmentId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  <input type="submit" value="Save"/>
}

<div>
  <div class="outside_side_bar">
    <div class="side_bar">
      <header>Epic Navi:</header>
      <br>
      <span>@Html.ActionLink("Back to List", "Index")</span>
      <br>
      <span>@Html.ActionLink("Home", "Index", "Home")</span>
    </div>
  </div>
</div>
<br>

Registrar/Views/Departments/Index.cshtml
@{
  Layout="_Layout";
}

@using Registrar.Models;

<h1>Departments for @User.Identity.Name</h1>

@if (@Model.Count == 0)
{
  <h3>No Courses have been added yet!</h3>
}

@foreach (Department department in Model)
{
  <li>@Html.ActionLink($"{department.Name}", "Details", new { id = department.DepartmentId})</li>
}

<div>
  <div class="outside_side_bar">
    <div class="side_bar">
      <header>SEptic Nasty:</header>
      <br>
      <span>@Html.ActionLink("Add new Department", "Create")</span>
      <br>
      <span>@Html.ActionLink("Home", "Index", "Home")</span>
    </div>
  </div>
</div>
<br>